name: Deploy Next.js static export to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAGES: "true"
      NPM_CONFIG_PRODUCTION: "false" # ensure devDependencies are installed
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Verify eslint availability
        run: |
          npx --yes which eslint || echo "eslint not found"
          npx --yes eslint --version || echo "eslint version not detected"

      - name: Lint
        run: npx eslint . --max-warnings=0

      - name: Restore Next.js cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: next-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            next-cache-${{ runner.os }}-

      - name: Build static export
        run: npm run pages:build

      - name: Add .nojekyll
        run: touch out/.nojekyll

      # Optional: custom domain
      # - name: Add CNAME
      #   run: echo "example.com" > out/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out
          retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
